// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7d5vR9pUuFXC6viyKF09yuhMH5LAtJJQ',
    appId: '1:101246305805:web:056a88e227388d68027744',
    messagingSenderId: '101246305805',
    projectId: 'driver-c7e27',
    authDomain: 'driver-c7e27.firebaseapp.com',
    storageBucket: 'driver-c7e27.firebasestorage.app',
    measurementId: 'G-4TGWWQD2MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR6uGIPgmKiBa0ApBcoDkhba-t3P-KMVo',
    appId: '1:101246305805:android:472217d0c9a1ffa7027744',
    messagingSenderId: '101246305805',
    projectId: 'driver-c7e27',
    storageBucket: 'driver-c7e27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfF2_-N3DSbFGyrMMrtTvi19Hjl_ToZxI',
    appId: '1:101246305805:ios:ab3eea4a3597c461027744',
    messagingSenderId: '101246305805',
    projectId: 'driver-c7e27',
    storageBucket: 'driver-c7e27.firebasestorage.app',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfF2_-N3DSbFGyrMMrtTvi19Hjl_ToZxI',
    appId: '1:101246305805:ios:ab3eea4a3597c461027744',
    messagingSenderId: '101246305805',
    projectId: 'driver-c7e27',
    storageBucket: 'driver-c7e27.firebasestorage.app',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7d5vR9pUuFXC6viyKF09yuhMH5LAtJJQ',
    appId: '1:101246305805:web:172892844e9f818c027744',
    messagingSenderId: '101246305805',
    projectId: 'driver-c7e27',
    authDomain: 'driver-c7e27.firebaseapp.com',
    storageBucket: 'driver-c7e27.firebasestorage.app',
    measurementId: 'G-FV7R9KZH28',
  );
}
